### ISSUE TITLE
Add some config options

### ISSUE THREAD

**Issue by mrmartineau** [adriankremer/rollup-plugin-proxy-directories#1]
First off, this is a great idea for a Rollup plugin. It is something that should be easier to do with modern build tools. Thanks.

My feature request has two parts, they are both related to inclusion/exclusion of certain items from being processed by your plugin:

1. Is it possible to allow only certain entry points to be included by this plugin? e.g. `./src/Button` but not `./src/Checkbox`

2. Is it possible to exclude certain files based on a globbing pattern? Having looked at the source code, I can see that you have something that ignores test files: https://github.com/adriankremer/rollup-plugin-proxy-directories/blob/master/src/index.js#L65-L67

For example, using `*.stories.tsx` would ignore all files like `Button.stories.tsx` from being considered as a entry point that should be bundled. Does that make sense?

**Comment by adriankremer** [comment]
Thanks ❤️
Currently it has no options to include / exclude (just that regex to filter for folders with a beginning underscore). But it definitely should, because currently it is all or nothing. If you like please feel free to contribute.

**Comment by mrmartineau** [comment]
I would love to help, can you give some pointers as to where I should start?

**Comment by mrmartineau** [comment]
FYI solves the same problem as this plugin
